# Generated by Django 3.2.9 on 2021-11-26 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.TextField(max_length=60)),
                ('quantity', models.TextField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=60)),
                ('price', models.TextField(max_length=60)),
                ('description', models.TextField(max_length=60)),
                ('picture', models.ImageField(upload_to='')),
                ('weight', models.TextField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.TextField(max_length=60)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzaStoreApp.cart')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzaStoreApp.pizza')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='pizza_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzaStoreApp.pizza'),
        ),
    ]
