# Generated by Django 3.2.9 on 2021-11-26 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaStoreApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaquantity',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzaStoreApp.pizza', unique=True),
        ),
    ]
