# Generated by Django 3.2.9 on 2021-11-27 20:00

from django.db import migrations, models
import pizzaStoreApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaStoreApp', '0003_auto_20211127_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzaquantity',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='pizzaquantity',
            name='id',
        ),
        migrations.AlterField(
            model_name='pizzaquantity',
            name='pizza',
            field=models.CharField(max_length=60, primary_key=pizzaStoreApp.models.Pizza, serialize=False),
        ),
        migrations.AlterField(
            model_name='pizzaquantity',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
