# Generated by Django 3.2.9 on 2021-11-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaStoreApp', '0004_auto_20211127_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaquantity',
            name='quantity',
            field=models.CharField(max_length=60),
        ),
    ]
