# Generated by Django 3.2.9 on 2021-11-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaStoreApp', '0006_auto_20211127_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaquantity',
            name='pizza',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
