# Generated by Django 3.2.9 on 2021-11-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaStoreApp', '0007_alter_pizzaquantity_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaquantity',
            name='quantity',
            field=models.IntegerField(max_length=60),
        ),
    ]
