# Generated by Django 3.2.9 on 2021-11-28 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaStoreApp', '0012_alter_pizzaquantity_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaquantity',
            name='pizza',
            field=models.ForeignKey(max_length=60, on_delete=django.db.models.deletion.CASCADE, to='pizzaStoreApp.pizza', unique=True),
        ),
    ]
