# Generated by Django 3.2.9 on 2021-11-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaStoreApp', '0014_alter_pizzaquantity_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.FloatField(max_length=60),
        ),
    ]
