# Generated by Django 3.2.9 on 2021-11-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaStoreApp', '0018_alter_order_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pizza',
        ),
        migrations.AddField(
            model_name='order',
            name='pizza',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
